all : A B C B E
A : A.cpp
	g++ -std=c++11 -o A A.cpp
B : B.cpp
	g++ -std=c++11 -o B B.cpp
C : C.cpp
	g++ -std=c++11 -o C C.cpp
D : D.cpp
	g++ -std=c++11 -o D D.cpp
E : E.cpp
	g++ -std=c++11 -o E E.cpp
